name: Remove Mobirise Ads

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  remove_ads:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Remove Mobirise ads from HTML files
      run: |
        find . -type f -name "*.html" -exec sed -i '/<section class="display-7" style="padding: 0;align-items: center;justify-content: center;flex-wrap: wrap;/{:a;N;/<\/section>/!ba;d}' {} +
    - name: Commit changes
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Remove Mobirise ads from HTML files" || echo "No changes to commit"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
